trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    pip install pandas numpy pyspark
  displayName: 'Install Dependencies'

- script: |
    python expense_analysis.py
  displayName: 'Run Expense Analysis'

- script: |
    echo "Monthly analysis completed"
  displayName: 'Completion Message'